---
title: "PcDESeq2"
author: "BWSchroeter"
date: "2023-05-22"
output: html_document
---

```{r, load libraries, include=FALSE}
library("kableExtra")
library(WGCNA)
library(DESeq2)
library(GEOquery)
library(tidyverse)
library(gridExtra)
library(reshape2)
library(rtracklayer)
library(dplyr)
library(edgeR)
library(clusterProfiler)
library(pheatmap)
library(RColorBrewer)
library("eulerr")
```

Upload files

```{r}
coldata <- read.table('sample_info.tsv')
Pcgenenames <- read.table('pcgeneids.tsv', row.names = 1, quote = "", sep='\t', fill = TRUE, header = TRUE)
IUM83Tanjilcountmatrix <- read.table('countmatrix.tsv') 

```

Clean countmatrix for P. cinnamomi analysis

```{r}
collabels <- colnames(IUM83Tanjilcountmatrix) <- (coldata$Sample)
colnames(IUM83Tanjilcountmatrix) <- collabels

IUM83Tanjilcountmatrix <- tibble::rownames_to_column(IUM83Tanjilcountmatrix, "gene_id")

IUM83CountMatrix <- IUM83Tanjilcountmatrix %>% 
  filter(str_detect(gene_id, "IUM83")) 
  
rownames(IUM83CountMatrix) <- IUM83CountMatrix$gene_id
IUM83CountMatrix <- IUM83CountMatrix [ ,-1]
IUM83CountMatrix <- as.data.frame(IUM83CountMatrix)
IUM83CountMatrix <- IUM83CountMatrix[ ,-(1:12)]

head(IUM83CountMatrix)
#write.table(IUM83CountMatrix, file = "Pc_countmatrix.tsv",quote=FALSE,sep="\t")
```
```{r}
summary(IUM83CountMatrix)
par(mar = c(8, 4, 4, 1) + 0.1)
barplot(colSums(IUM83CountMatrix)/1e6, las = 3)

```


```{r}
IUM83LogCountMatrix <- log2(1+IUM83CountMatrix)

hist(IUM83LogCountMatrix, br = 100)

```

Clean coldata for Deseq2 normalisation

```{r}
colData <- coldata %>% 
  filter(str_detect(Sample, "Pc"))

rownames(colData) <- colData$Sample
colData <- colData [ ,-1] 

# making sure the row names in colData matches to column names in counts_data
all(colnames(IUM83CountMatrix) %in% rownames(colData))
```

```{r}
# Create sample information
sampleNames <- colData$Sample
condition <- colData$Stage
timepoint <- colData$Time

colDATA <- data.frame(sampleNames,
                      condition,
                      timepoint,
                      stringsAsFactors = T)

# Create the DESeqDataSet object
dds <- DESeqDataSetFromMatrix(countData = IUM83CountMatrix,
                              colData = colDATA,
                              design = ~ condition)

nrow(dds)
dds <- dds[rowMeans(counts(dds)) >10,]
nrow(dds)

```

```{r}
vsd <- vst(dds, blind = FALSE)
head(assay(vsd), 3)

rld <- rlog(dds, blind = FALSE)
head(assay(rld), 3)
                    
```

```{r}
ds <- estimateSizeFactors(dds)

df <- bind_rows(
  as.data.frame(log2(counts(dds, normalized=F)[, 1:2]+1)) %>%
         mutate(transformation = "log2(x + 1)"),
  as.data.frame(assay(vsd)[, 1:2]) %>% mutate(transformation = "vst"),
  as.data.frame(assay(rld)[, 1:2]) %>% mutate(transformation = "rlog"))
  
colnames(df)[1:2] <- c("x", "y")  

lvls <- c("log2(x + 1)", "vst", "rlog")
df$transformation <- factor(df$transformation, levels=lvls)

ggplot(df, aes(x = x, y = y)) + geom_hex(bins = 80) +
  coord_fixed() + facet_grid( . ~ transformation) 
```

```{r}
sampleDists <- dist(t(assay(rld)))
sampleDists

sampleDistMatrix <- as.matrix( sampleDists )
rownames(sampleDistMatrix) <- paste( vsd$dex, vsd$cell, sep = " - " )
colnames(sampleDistMatrix) <- NULL
colors <- colorRampPalette( rev(brewer.pal(9, "Blues")) )(255)

pheatmap(sampleDistMatrix,
         clustering_distance_rows = sampleDists,
         clustering_distance_cols = sampleDists,
         col = colors)

```
```{r}

PCA <- plotPCA(rld, c("timepoint", "sampleNames"), returnData = TRUE)
percentVar <- round(100 * attr(PCA, "percentVar"))

ggplot(PCA, aes(PC1, PC2, color = condition)) +
  geom_point(size = 5) +
  geom_point(shape = 21, fill = "transparent", colour = "black", size = 5) +
  xlab(paste0("PC1 (", percentVar[1], "%)")) +
  ylab(paste0("PC2 (", percentVar[2], "%)")) +
  coord_fixed() +
  theme_bw() +
  theme(axis.line = element_line(color = "black"),
        panel.border = element_rect(color = "black"),
        panel.grid.major = element_line(color = "grey"),  # Set the color of major grid lines to grey
        panel.grid.minor = element_blank(),
        legend.position = c(0.05, 0.40),  # Set the position of the legend (top-left corner)
        legend.justification = c(0, 1),  # Set the justification of the legend (top-left corner)
        legend.background = element_rect(color = "black", fill = "white", size = 0.5),  # Add a black border around the legend box and make it white
        legend.key.size = unit(1, "lines"))  # Increase the size of the legend key

```

```{r}
sampleDists <- dist(t(assay(vsd)))
sampleDists

sampleDistMatrix <- as.matrix( sampleDists )
rownames(sampleDistMatrix) <- paste( vsd$dex, vsd$cell, sep = " - " )
colnames(sampleDistMatrix) <- NULL
colors <- colorRampPalette( rev(brewer.pal(9, "Blues")) )(255)
pheatmap(sampleDistMatrix,
         clustering_distance_rows = sampleDists,
         clustering_distance_cols = sampleDists,
         col = colors)

```

```{r}

PCA <- plotPCA(vsd, c("timepoint", "sampleNames"), returnData = TRUE)
percentVar <- round(100 * attr(PCA, "percentVar"))

ggplot(PCA, aes(PC1, PC2, color = condition)) +
  geom_point(size = 5) +
  geom_point(shape = 21, fill = "transparent", colour = "black", size = 5) +
  xlab(paste0("PC1 (", percentVar[1], "%)")) +
  ylab(paste0("PC2 (", percentVar[2], "%)")) +
  coord_fixed() +
  theme_bw() +
  theme(axis.line = element_line(color = "black"),
        panel.border = element_rect(color = "black"),
        panel.grid.major = element_line(color = "grey"),  
        panel.grid.minor = element_blank(),
        legend.position = c(0.05, 0.95),  
        legend.justification = c(0, 1),  
        legend.background = element_rect(color = "black", fill = "white", size = 0.5), 
        legend.key.size = unit(1, "lines"))  

```

```{r}

filename <- "PCA_vst.png"
png(filename)

width <- 10  
height <- 6  

png(filename, width = width, height = height, units = "in", res = 300)

ggplot(PCA, aes(PC1, PC2, color = condition)) +
  geom_point(size = 5) +
  geom_point(shape = 21, fill = "transparent", colour = "black", size = 5) +
  xlab(paste0("PC1 (", percentVar[1], "%)")) +
  ylab(paste0("PC2 (", percentVar[2], "%)")) +
  coord_fixed() +
  theme_bw() +
  theme(axis.line = element_line(color = "black"),
        panel.border = element_rect(color = "black"),
        panel.grid.major = element_line(color = "grey"),  
        panel.grid.minor = element_blank(),
        legend.position = c(0.05, 0.95),  
        legend.justification = c(0, 1),  
        legend.background = element_rect(color = "black", fill = "white", size = 0.5),
        legend.key.size = unit(1, "lines"))  

dev.off()
```

```{r}
dds$condition <- relevel(dds$timepoint, ref = "0h")

dds <- DESeq(dds)

as.data.frame(colData(dds))
```

```{r}
# To compare "Early" vs "Vegetative"
res_early_vs_vegetative <- results(dds, contrast = c("condition", "18h", "0h"))

# Arrange the results by p-value
res_early_vs_vegetative <- res_early_vs_vegetative[order(res_early_vs_vegetative$pvalue), ]
summary(res_early_vs_vegetative)
res_early_vs_vegetative

eup <- rownames(subset(res_early_vs_vegetative, log2FoldChange > 2 & padj < 0.05))
edn <- rownames(subset(res_early_vs_vegetative, log2FoldChange < 2 & padj < 0.05))

# Print the number of upregulated and downregulated genes
str(eup)
str(edn)

# MA plot
sig <- subset(res_early_vs_vegetative, padj < 0.05)
GENESUP <- length(eup)
GENESDN <- length(edn)
SUBHEADER <- paste(GENESUP, "up, ", GENESDN, "down")

# Create the MA plot
plot(log2(res_early_vs_vegetative$baseMean), res_early_vs_vegetative$log2FoldChange,
     xlab = "log2 basemean", ylab = "log2 foldchange",
     pch = 19, cex = 0.5, col = "dark gray",
     main = "smear plot")
points(log2(sig$baseMean), sig$log2FoldChange,
       pch = 19, cex = 0.5, col = "blue")
mtext(SUBHEADER)
```

```{r, Top 50 most significant genes based on p-value - Early}
 
top_genes <- head(res_early_vs_vegetative[order(res_early_vs_vegetative$pvalue), ], 50)

# Extract the expression values for the top genes
top_gene_expression <- assay(dds)[rownames(top_genes), ]

# Create a matrix of log2-transformed expression values
log2_expression <- log2(top_gene_expression + 1)

# Extract the expression values for the top genes and select columns 1 to 6
top_gene_expression_early <- top_gene_expression[, 1:6]

# Create a matrix of log2-transformed expression values
log2_expression_early <- log2(top_gene_expression_early + 1)

filename <- "Early_pheatmap.png"
width <- 4800 
height <- 4800
pointsize <- 10
resolution <- 600

png(filename, width = width, height = height, pointsize = pointsize, res = resolution)

col_ann <- colData[,c(1,4)]
rownames(col_ann) <- col_ann$Sample
col_ann <- data.frame(col_ann)
col_ann$Stage <- as.factor(col_ann$Stage)
col_ann <- col_ann[order(col_ann$Stage),]
col_ann$sample_ID <- NULL
head(col_ann, 12)

pheatmap(top_gene_expression_early,  scale = "row",
         cluster_rows = TRUE, cluster_cols = T,
         display_numbers = F, 
         fontsize_row = 8, fontsize_col = 8, 
         annotation_col = col_ann,
         show_colnames = FALSE,
         cellheight = 8, cellwidth = 40,
         main = "Early interaction")

dev.off()

```

```{r}
# To compare "Middle" vs "Vegetative"
res_middle_vs_vegetative <- results(dds, contrast =c ("condition", "30h", "0h"))
summary(res_middle_vs_vegetative)
res_middle_vs_vegetative
 
mup <- rownames(subset(res_middle_vs_vegetative, log2FoldChange > 1 & padj < 0.05))
mdn <- rownames(subset(res_middle_vs_vegetative, log2FoldChange < 1 & padj < 0.05))

# Print the number of upregulated and downregulated genes
str(mup)
str(mdn)

# MA plot
sig <- subset(res_middle_vs_vegetative, padj < 0.05)
GENESUP <- length(mup)
GENESDN <- length(mdn)
SUBHEADER <- paste(GENESUP, "up, ", GENESDN, "down")

# Create the MA plot
plot(log2(res_middle_vs_vegetative$baseMean), res_middle_vs_vegetative$log2FoldChange,
     xlab = "log2 basemean", ylab = "log2 foldchange",
     pch = 19, cex = 0.5, col = "dark gray",
     main = "smear plot")
points(log2(sig$baseMean), sig$log2FoldChange,
       pch = 19, cex = 0.5, col = "green")
mtext(SUBHEADER)
```

```{r, Top 50 most significant genes based on p-value - Middle}

top_genes <- head(res_middle_vs_vegetative[order(res_middle_vs_vegetative$pvalue), ], 50)

# Extract the expression values for the top genes
top_gene_expression <- assay(dds)[rownames(top_genes), ]

# Create a matrix of log2-transformed expression values
log2_expression <- log2(top_gene_expression + 1)

# Extract the expression values for the top genes and the selected columns (1 to 3 and 7 to 9)
top_gene_expression_middle <- assay(dds)[rownames(top_genes), c(1:3, 7:9)]

# Create a matrix of log2-transformed expression values
log2_expression_middle <- log2(top_gene_expression_middle + 1)

filename <- "Mid_pheatmap.png"
width <- 4800 
height <- 4800
pointsize <- 10
resolution <- 600

png(filename, width = width, height = height, pointsize = pointsize, res = resolution)

col_ann <- colData[,c(1,4)]
rownames(col_ann) <- col_ann$Sample
col_ann <- data.frame(col_ann)
col_ann$Stage <- as.factor(col_ann$Stage)
col_ann <- col_ann[order(col_ann$Stage),]
col_ann$sample_ID <- NULL
head(col_ann, 12)

pheatmap(log2_expression_middle,  scale = "row",
         cluster_rows = TRUE, cluster_cols = T,
         display_numbers = F, 
         fontsize_row = 8, fontsize_col = 8, 
         annotation_col = col_ann,
         show_colnames = FALSE,
         cellheight = 8, cellwidth = 40,
         main = "Top 50 Genes by p-value (Middle)")

dev.off()
```

```{r}
# To compare "Late" vs "Vegetative"
res_late_vs_vegetative <- results(dds, contrast = c("condition", "48h", "0h"))
summary(res_late_vs_vegetative)
(res_late_vs_vegetative)

lup <- rownames(subset(res_late_vs_vegetative, log2FoldChange > 2 & padj < 0.05))
ldn <- rownames(subset(res_late_vs_vegetative, log2FoldChange < 2 & padj < 0.05))

# Print the number of upregulated and downregulated genes
str(lup)
str(ldn)

# MA plot
sig <- subset(res_late_vs_vegetative, padj < 0.05)
GENESUP <- length(lup)
GENESDN <- length(ldn)
SUBHEADER <- paste(GENESUP, "up, ", GENESDN, "down")

# Create the MA plot
plot(log2(res_late_vs_vegetative$baseMean), res_late_vs_vegetative$log2FoldChange,
     xlab = "log2 basemean", ylab = "log2 foldchange",
     pch = 19, cex = 0.5, col = "dark gray",
     main = "smear plot")
points(log2(sig$baseMean), sig$log2FoldChange,
       pch = 19, cex = 0.5, col = "blue")
mtext(SUBHEADER)
```

```{r}
# Get the top 50 most significant genes based on p-value
top_genes <- head(res_late_vs_vegetative[order(res_late_vs_vegetative$pvalue), ], 50)

# Extract the expression values for the top genes and the selected columns (1 to 3 and 10 to 12)
top_gene_expression_late <- assay(dds)[rownames(top_genes), c(1:3, 10:12)]

# Create a matrix of log2-transformed expression values
log2_expression_late <- log2(top_gene_expression_late + 1)

col_ann <- colData[,c(1,4)]
rownames(col_ann) <- col_ann$Sample
col_ann <- data.frame(col_ann)
col_ann$Stage <- as.factor(col_ann$Stage)
col_ann <- col_ann[order(col_ann$Stage),]
col_ann$sample_ID <- NULL
head(col_ann, 12)

#filename <- "Late_pheatmap.png"
#width <- 4800 
#height <- 4800
#pointsize <- 10
#resolution <- 600

png(filename = "Late_pheatmap.png", width = 4800, height = 4800, pointsize = 10, res = 600)

pheatmap(log2_expression_late,  scale = "row",
         cluster_rows = TRUE, cluster_cols = T,
         display_numbers = F, 
         fontsize_row = 8, fontsize_col = 8, 
         annotation_col = col_ann,
         show_colnames = FALSE,
         cellheight = 8, cellwidth = 40,
         main = "Top 50 Genes by p-value (Late)")
       
dev.off()
```

        



```{r, Mitch input}
earlymitch <- as.data.frame(res_early_vs_vegetative)
midmitch <- as.data.frame(res_middle_vs_vegetative)
latemitch <- as.data.frame(res_late_vs_vegetative)

#save(earlymitch, midmitch, latemitch, file = "PcMitch.RData")
```

### 
PcEFFECTOR analysis
###

```{r, Effector input}
#save detected genes to export to PcEffector.Rmd
detectedgenes <- results(dds)
detectedgenes <- as.data.frame(detectedgenes)
#save(detectedgenes, file = "Pceffetor.RData")

```

```{r}
#import the results to use in MA plots
load("/mnt/data/barry/projects/Schroeter_Pcinnamomi/PcEffector/secrete.effect.RData")
```

```{r, secretome expression}
earlydetected <- as.data.frame(res_early_vs_vegetative)
earlydetected$gene_id <- rownames(earlydetected)
earlysecreted <- dplyr::right_join(earlydetected, pts.id, by = 'gene_id')

middetected <- as.data.frame(res_middle_vs_vegetative)
middetected$gene_id <- rownames(middetected)
midsecreted <- dplyr::right_join(middetected, pts.id, by = 'gene_id')

latedetected <- as.data.frame(res_late_vs_vegetative)
latedetected$gene_id <- rownames(latedetected)
latesecreted <- dplyr::right_join(latedetected, pts.id, by = 'gene_id')

```

```{r, secretome eulerr plot}

eeup <- unique(earlysecreted[earlysecreted$log2FoldChange > 0 & earlysecreted$padj < 0.05, ])
eeup <- eeup$gene_id
eedn <- unique(earlysecreted[earlysecreted$log2FoldChange < 0 & earlysecreted$padj < 0.05, ])
eedn <- eedn$gene_id

meup <- unique(midsecreted[midsecreted$log2FoldChange > 0 & midsecreted$padj < 0.05, ])
meup <- meup$gene_id
medn <- unique(midsecreted[midsecreted$log2FoldChange < 0 & midsecreted$padj < 0.05, ])
medn <- medn$gene_id

leup <- unique(latesecreted[latesecreted$log2FoldChange > 0 & latesecreted$padj < 0.05, ])
leup <- leup$gene_id
ledn <- unique(latesecreted[latesecreted$log2FoldChange < 0 & latesecreted$padj < 0.05, ])
ledn <- ledn$gene_id


v1 <- list("Earlyup"=eeup, "Earlydn"=eedn, "Midup"=meup, "Middn"=medn, "Lateup"=leup,"Latedn"=ledn)

plot(euler(v1),labels = list(cex=2),quantities = list(cex=2), main="Predicted secterome expression")
```

```{r, effector expression}
earlydetected <- as.data.frame(res_early_vs_vegetative)
earlydetected$gene_id <- rownames(earlydetected)
earlysecreted <- dplyr::right_join(earlydetected, predictedeffectors2.id, by = 'gene_id')

middetected <- as.data.frame(res_middle_vs_vegetative)
middetected$gene_id <- rownames(middetected)
midsecreted <- dplyr::right_join(middetected, predictedeffectors2.id, by = 'gene_id')

latedetected <- as.data.frame(res_late_vs_vegetative)
latedetected$gene_id <- rownames(latedetected)
latesecreted <- dplyr::right_join(latedetected, predictedeffectors2.id, by = 'gene_id')

```

```{r, effector eulerr plot}

eeup <- unique(earlysecreted[earlysecreted$log2FoldChange > 0 & earlysecreted$padj < 0.05, ])
eeup <- eeup$gene_id
eedn <- unique(earlysecreted[earlysecreted$log2FoldChange < 0 & earlysecreted$padj < 0.05, ])
eedn <- eedn$gene_id

meup <- unique(midsecreted[midsecreted$log2FoldChange > 0 & midsecreted$padj < 0.05, ])
meup <- meup$gene_id
medn <- unique(midsecreted[midsecreted$log2FoldChange < 0 & midsecreted$padj < 0.05, ])
medn <- medn$gene_id

leup <- unique(latesecreted[latesecreted$log2FoldChange > 0 & latesecreted$padj < 0.05, ])
leup <- leup$gene_id
ledn <- unique(latesecreted[latesecreted$log2FoldChange < 0 & latesecreted$padj < 0.05, ])
ledn <- ledn$gene_id

v1 <- list("Earlyup"=eeup, "Earlydn"=eedn, "Midup"=meup, "Middn"=medn, "Lateup"=leup,"Latedn"=ledn)

plot(euler(v1),labels = list(cex=2),quantities = list(cex=2), main="Predicted secretome expression")
```


```{r, effector ORA}
apop <- predictedeffectors2.id[grep("Y", predictedeffectors2.id$Apoplastic_effector),]
apop.set <- data.frame("Apoplastic", apop$gene_id)
colnames(apop.set) <- c("term", "gene")

cyto <- predictedeffectors2.id[grep("Y", predictedeffectors2.id$Cytoplasmic_effector),]
cyto.set <- data.frame("Cytosolic", cyto$gene_id) 
colnames(cyto.set) <- c("term", "gene")

all.set <- data.frame("All_effectors", predictedeffectors2.id$gene_id)
colnames(all.set) <- c("term", "gene")

bg <- allgenes$gene_id
bg.set <- data.frame("background", bg)
colnames(bg.set) <- c("term", "gene")

sets <- rbind(apop.set, cyto.set, all.set, bg.set)

intup <- intersect(intersect(eeup, meup), leup)
esdup <- setdiff(eeup, intup)
intdn <- intersect(intersect(eedn, medn), ledn)
```

```{r}
ora_res <- as.data.frame(enricher(gene = intup,
                                    universe = bg,
                                    maxGSSize = 50000,
                                    TERM2GENE = sets,
                                    pAdjustMethod = "fdr",
                                    pvalueCutoff = 1,
                                    qvalueCutoff = 1))

ora_res$geneID <- NULL
  ora_res_names <- rownames(ora_res)
  
  ora_res$GeneRatio <- as.character(ora_res$GeneRatio)
  
  gr <- as.numeric(sapply(strsplit(as.character(ora_res$GeneRatio), "/"), "[[", 1)) /
    as.numeric(sapply(strsplit(as.character(ora_res$GeneRatio), "/"), "[[", 2))
  
  br <- as.numeric(sapply(strsplit(as.character(ora_res$BgRatio), "/"), "[[", 1)) /
    as.numeric(sapply(strsplit(as.character(ora_res$BgRatio), "/"), "[[", 2))
  
  ora_res$es <- gr/br
  ora_res <- ora_res[order(-ora_res$es), ]
  ora_res$Description <- NULL
  
view(ora_res)  
```

```{r}
# Create the MA plot
plot(log2(res_early_vs_vegetative$baseMean), res_early_vs_vegetative$log2FoldChange,
     xlab = "log2 basemean", ylab = "log2 foldchange",
     pch = 19, cex = 0.5, col = "dark gray",
     main = "Early")
points(log2(sig$baseMean), sig$log2FoldChange,
       pch = 19, cex = 0.5, col = "blue")


mtext(SUBHEADER)  
```

```{r,volc1}
# Set the filename for the PNG file
filename <- "Early_smear_plot.png"

plot(res_early_vs_vegetative$log2FoldChange, -log10(res_early_vs_vegetative$padj),
     xlab = "log2foldchange", ylab = "log10 p-value",
     pch = 19, cex = 0.5, col = "dark gray",
     main = "smear plot")
points(sig$log2FoldChange, -log10(sig$padj),
       pch = 19, cex = 0.5, col = "red")
points(earlysecreted$log2FoldChange, -log10(earlysecreted$padj),
       pch = 19, cex = 0.5, col = "blue")
points(eeffector$log2FoldChange, -log10(eeffector$padj),
       pch = 19, cex = 0.5, col = "green")
mtext(SUBHEADER) 

dev.off()
```

```{r}
middetected <- as.data.frame(res_middle_vs_vegetative)
middetected$gene_id <- rownames(middetected)

midsecreted <- dplyr::right_join(middetected, effectorp.results.id, by = 'gene_id')

meffector <- subset(midsecreted, !Prediction %in% "Non-effector")

res_mid_secreted <- midsecreted[order(midsecreted$pvalue), ]

mup <- rownames(subset(res_middle_vs_vegetative, log2FoldChange > 2 & padj < 0.05))
mdn <- rownames(subset(res_middle_vs_vegetative, log2FoldChange < 2 & padj < 0.05))

meup <- rownames(subset(meffector, log2FoldChange > 2 & padj < 0.05))
medn <- rownames(subset(meffector, log2FoldChange < 2 & padj < 0.05))
# Print the number of upregulated and downregulated genes
str(mup)
str(mdn)
str(meup)
str(medn)


msig <- subset(res_middle_vs_vegetative, padj < 0.05)
MGENESUP <- length(mup)
MGENESDN <- length(mdn)
MSUBHEADER <- paste("Mid", MGENESUP, "up, ", MGENESDN, "down")


# Create the MA plot
plot(log2(res_middle_vs_vegetative$baseMean), res_middle_vs_vegetative$log2FoldChange,
     xlab = "log2 basemean", ylab = "log2 foldchange",
     pch = 19, cex = 0.5, col = "dark gray",
     main = "smear plot")
points(log2(msig$baseMean), msig$log2FoldChange,
       pch = 19, cex = 0.5, col = "red")
points(log2(midsecreted$baseMean), midsecreted$log2FoldChange,
       pch = 19, cex = 0.5, col = "blue")
points(log2(meffector$baseMean), meffector$log2FoldChange,
       pch = 19, cex = 0.5, col = "green")
mtext(MSUBHEADER)
```

```{r,volc2}
# Set the filename for the PNG file
filename <- "Mid_smear_plot.png"

# Create a PNG device
png(filename)
plot(res_middle_vs_vegetative$log2FoldChange, -log10(res_middle_vs_vegetative$padj),
     xlab = "log2foldchange", ylab = "log10 p-value",
     pch = 19, cex = 0.5, col = "dark gray",
     main = "smear plot")
points(msig$log2FoldChange, -log10(msig$padj),
       pch = 19, cex = 0.5, col = "red")
points(midsecreted$log2FoldChange, -log10(midsecreted$padj),
       pch = 19, cex = 0.5, col = "blue")
points(meffector$log2FoldChange, -log10(meffector$padj),
       pch = 19, cex = 0.5, col = "green")
mtext(MSUBHEADER)

dev.off()
```


```{r}
latedetected <- as.data.frame(res_late_vs_vegetative)
latedetected$gene_id <- rownames(latedetected)

latesecreted <- dplyr::right_join(latedetected, effectorp.results.id, by = 'gene_id')

leffector <- subset(latesecreted, !Prediction %in% "Non-effector")


res_late_secreted <- latesecreted[order(latesecreted$pvalue), ]

lup <- rownames(subset(res_late_vs_vegetative, log2FoldChange > 2 & padj < 0.05))
ldn <- rownames(subset(res_late_vs_vegetative, log2FoldChange < 2 & padj < 0.05))

leup <- rownames(subset(leffector, log2FoldChange > 2 & padj < 0.05))
ledn <- rownames(subset(leffector, log2FoldChange < 2 & padj < 0.05))

# Print the number of upregulated and downregulated genes
str(lup)
str(ldn)

lsig <- subset(res_late_vs_vegetative, padj < 0.05)
LGENESUP <- length(lup)
LGENESDN <- length(ldn)
LSUBHEADER <- paste("Late", LGENESUP, "up, ", LGENESDN, "down")


# Create the MA plot
plot(log2(res_late_vs_vegetative$baseMean), res_late_vs_vegetative$log2FoldChange,
     xlab = "log2 basemean", ylab = "log2 foldchange",
     pch = 19, cex = 0.5, col = "dark gray",
     main = "smear plot")
points(log2(lsig$baseMean), lsig$log2FoldChange,
       pch = 19, cex = 0.5, col = "red")
points(log2(latesecreted$baseMean), latesecreted$log2FoldChange,
       pch = 19, cex = 0.5, col = "blue")
points(log2(leffector$baseMean), leffector$log2FoldChange,
       pch = 19, cex = 0.5, col = "green")
mtext(LSUBHEADER)
```

```{r}
# Set the filename for the PNG file
filename <- "Late_smear_plot.png"

# Create a PNG device
png(filename)

# Generate the plot
plot(res_late_vs_vegetative$log2FoldChange, -log10(res_late_vs_vegetative$padj),
     xlab = "log2foldchange", ylab = "log10 p-value",
     pch = 19, cex = 0.5, col = "dark gray",
     main = "smear plot")
points(lsig$log2FoldChange, -log10(lsig$padj),
       pch = 19, cex = 0.5, col = "red")
points(latesecreted$log2FoldChange, -log10(latesecreted$padj),
       pch = 19, cex = 0.5, col = "blue")
mtext("Late")

# Close the PNG device
dev.off()
```

```{r, combined volcano}

# Set the filename for the PNG file
filename <- "combinedvolcano_plots.png"

# Create a PNG device for the combined plot
png(filename)

width <- 10  # Adjust the width as desired
height <- 6  # Adjust the height as desired

# Create a PNG device for the combined plot with increased dimensions
png(filename, width = width, height = height, units = "in", res = 300)


# Set the layout for the plots (1 row, 3 columns)
par(mfrow = c(1, 3))

plot(res_early_vs_vegetative$log2FoldChange, -log10(res_early_vs_vegetative$padj),
     xlab = "log2foldchange", ylab = "log10 p-value",
     pch = 19, cex = 0.5, col = "dark gray",
     main = "smear plot")
points(sig$log2FoldChange, -log10(sig$padj),
       pch = 19, cex = 0.5, col = "red")
points(earlysecreted$log2FoldChange, -log10(earlysecreted$padj),
       pch = 19, cex = 0.5, col = "blue")
points(eeffector$log2FoldChange, -log10(eeffector$padj),
       pch = 19, cex = 0.5, col = "black")
mtext("Early")

plot(res_middle_vs_vegetative$log2FoldChange, -log10(res_middle_vs_vegetative$padj),
     xlab = "log2foldchange", ylab = "log10 p-value",
     pch = 19, cex = 0.5, col = "dark gray",
     main = "smear plot")
points(msig$log2FoldChange, -log10(msig$padj),
       pch = 19, cex = 0.5, col = "red")
points(midsecreted$log2FoldChange, -log10(midsecreted$padj),
       pch = 19, cex = 0.5, col = "blue")
points(meffector$log2FoldChange, -log10(meffector$padj),
       pch = 19, cex = 0.5, col = "black")
mtext("Mid")

plot(res_late_vs_vegetative$log2FoldChange, -log10(res_late_vs_vegetative$padj),
     xlab = "log2foldchange", ylab = "log10 p-value",
     pch = 19, cex = 0.5, col = "dark gray",
     main = "smear plot")
points(lsig$log2FoldChange, -log10(lsig$padj),
       pch = 19, cex = 0.5, col = "red")
points(latesecreted$log2FoldChange, -log10(latesecreted$padj),
       pch = 19, cex = 0.5, col = "blue")
points(leffector$log2FoldChange, -log10(leffector$padj),
       pch = 19, cex = 0.5, col = "black")
mtext("Late")

# Close the PNG device
dev.off()
```

```{r}
# Set the filename for the PNG file
filename <- "combinedMA_plots.png"

# Create a PNG device for the combined plot
png(filename)

width <- 10  # Adjust the width as desired
height <- 6  # Adjust the height as desired

# Create a PNG device for the combined plot with increased dimensions
png(filename, width = width, height = height, units = "in", res = 300)

# Set the layout for the plots (1 row, 3 columns)
par(mfrow = c(1, 3))

plot(log2(res_early_vs_vegetative$baseMean), res_early_vs_vegetative$log2FoldChange,
     xlab = "log2 basemean", ylab = "log2 foldchange",
     pch = 19, cex = 0.5, col = "dark gray",
     main = "smear plot")
points(log2(sig$baseMean), sig$log2FoldChange,
       pch = 19, cex = 0.5, col = "red")
points(log2(earlysecreted$baseMean), earlysecreted$log2FoldChange,
       pch = 19, cex = 0.5, col = "blue")
mtext(SUBHEADER)

plot(log2(res_middle_vs_vegetative$baseMean), res_middle_vs_vegetative$log2FoldChange,
     xlab = "log2 basemean", ylab = "log2 foldchange",
     pch = 19, cex = 0.5, col = "dark gray",
     main = "smear plot")
points(log2(msig$baseMean), msig$log2FoldChange,
       pch = 19, cex = 0.5, col = "red")
points(log2(midsecreted$baseMean), midsecreted$log2FoldChange,
       pch = 19, cex = 0.5, col = "blue")
mtext(MSUBHEADER)

plot(log2(res_late_vs_vegetative$baseMean), res_late_vs_vegetative$log2FoldChange,
     xlab = "log2 basemean", ylab = "log2 foldchange",
     pch = 19, cex = 0.5, col = "dark gray",
     main = "smear plot")
points(log2(lsig$baseMean), lsig$log2FoldChange,
       pch = 19, cex = 0.5, col = "red")
points(log2(latesecreted$baseMean), latesecreted$log2FoldChange,
       pch = 19, cex = 0.5, col = "blue")
points(leffector$log2FoldChange, -log10(leffector$padj),
       pch = 19, cex = 0.5, col = "green")
mtext(LSUBHEADER)

dev.off()
```

## Session information

```{r,session}

sessionInfo()

```
